#!/bin/bash

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`

regexp="(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?!?: .+"

echo "Checking for Conventional Commit for message:"
echo $START_LINE

if [[ $START_LINE =~ $regexp ]]
then
    echo "Convention upheld"
    exit 0
else
    echo "Commit Message not Conventional"
    exit 1
fi

