#!/usr/bin/env bash

echo '#
# Conventional Commit Specification:
# types: build ci docs feat fix perf refactor style test chore revert
# max length (first line): 100
# min length (first line): 10
#
# structure:
# <type>[optional scope]: <description>
#
# [optional body]
# 
# [optional footer(s)]
#
# Find more information on: https://www.conventionalcommits.org/en/v1.0.0/#summary' >> $1
